fix(Text Column Formatting): Formatting not working in Measures in Rows VBI-5575
visualbis/draftjs pull request #152
Opened 2023-07-27 06:55 UTC by vishnu-varthanan

# Changes Made On Draft Editor

1.  [ ] Editor
2.  [ ] Toolbar

# Purpose of change

-   [ ] NEW FEATURE IMPLEMENTATION
-   [ ] CODE QUALITY IMPROVEMENT
-   [ ] BUG FIX
-   [ ] Version Updation

# Description of change

# Reviewer

2023-07-27 09:30 UTC, hb1998 requested changes
after the required changes are made, make sure you get a new version from devaraj and update it in ibcslibrary, and test the fix once

2023-07-28 07:09 UTC, vishnu-varthanan commented on src/DraftApi.ts
> +        const applyFormat = formatValue && !inlineStyles.has(formatType.toUpperCase());
Okay

2023-07-28 08:01 UTC, nsdevaraj commented
Send PR to 2.4

2023-08-17 16:23 UTC, hb1998 approved these changes
LGTM

2023-08-17 16:24 UTC, merged